// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsusgmtoeexkishknfel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzdXNnbXRvZWV4a2lzaGtuZmVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MzA1MDYsImV4cCI6MjA2NDAwNjUwNn0.XorVBJOSjyPV1CFBOEQtDNvthykK_HtYNKeVvRkMm9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);